# Generated by Django 4.0.3 on 2023-01-04 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_moviesdata_typ'),
    ]

    operations = [
        migrations.AddField(
            model_name='moviesdata',
            name='image',
            field=models.ImageField(default='Images/None/no_img.png', upload_to='Images'),
        ),
    ]
